version: 2
jobs:
  build:
    docker:
      - image: codeforamerica/bear-ci

    working_directory: ~/bear

    steps:
      - checkout

      - run:
          name: Fetch gogen binary
          command: |
            export TOKEN=$GITHUB_ACCESS_TOKEN
            mkdir -p ~/go/bin
            bash ~/bear/.circleci/github_download_release.sh "latest" ~/go/bin/gogen
            chmod +x ~/go/bin/gogen

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run unit tests
          command: yarn build && yarn test

      - run:
          name: Run end-to-end tests
          command: START_MINIMIZED=true yarn build-e2e && yarn test-e2e

  package:
    docker:
      - image: codeforamerica/bear-ci

    working_directory: ~/bear

    steps:
      - checkout

      - run:
          name: Fetch gogen binary
          command: |
            export TOKEN=$GITHUB_ACCESS_TOKEN
            export FILE=gogen_win.exe
            bash ~/bear/.circleci/github_download_release.sh "latest" ./gogen.exe

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build and Publish for Windows
          command: |
            yarn package-publish-win

workflows:
  version: 2
  build-and-package:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - package:
          requires:
            - hold
