version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14-browsers

      - image: circleci/golang:1.12.1

    working_directory: ~/bear

    steps:
      - checkout

      - run:
          name: Clone gogen repository
          command: git clone git@github.com:codeforamerica/gogen ~/go/src/gogen

      - run:
          name: Build gogen binary
          command: cd ~/go/src/gogen && go get ./... && go build

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run unit tests
          command: yarn build && yarn test

      - run:
          name: Run end-to-end tests
          command: START_MINIMIZED=true yarn build-e2e && yarn test-e2e

      - store_test_results:
          path: /tmp/test-results
