version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14

    working_directory: ~/repo

    steps:
      #      - add_ssh_keys:
      #          fingerprints:
      #            - "4d:c5:9b:a8:fe:49:2b:c8:59:e0:58:f1:a7:33:06:ff"

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test-all
